name: ${project.name}
author: ${author}
version: ${project.version}(built ${timestamp})
main: ${project.groupId}.${project.artifactId}.HorseStatsMain

api-version: 1.13

commands:
  horsestats:
    description: "Show's current stats for the entity you are currently riding"
    aliases: ['hs']
